name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      DEVICE:
        description: '选择要编译的设备型号'
        required: true
        default: 'jdcloud_re-sp-01b'
        type: choice
        options:
          - jdcloud_re-sp-01b
          - xiaomi_mi-router-4a-gigabit
          - xiaomi_mi-router-ac2100
          - netgear_r6220

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt -b openwrt-24.10 openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate .config for selected device
      run: |
        cd openwrt
        DEVICE="${{ github.event.inputs.DEVICE }}"
        echo "正在为 $DEVICE 生成 .config"

        case $DEVICE in
          jdcloud_re-sp-01b)
            echo "CONFIG_TARGET_ramips=y" >> .config
            echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
            echo "CONFIG_TARGET_DEVICE_ramips_mt7621_DEVICE_jdcloud_re-sp-01b=y" >> .config
            ;;
          xiaomi_mi-router-4a-gigabit)
            echo "CONFIG_TARGET_ramips=y" >> .config
            echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
            echo "CONFIG_TARGET_DEVICE_ramips_mt7621_DEVICE_xiaomi_mi-router-4a-gigabit=y" >> .config
            ;;
          xiaomi_mi-router-ac2100)
            echo "CONFIG_TARGET_ramips=y" >> .config
            echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
            echo "CONFIG_TARGET_DEVICE_ramips_mt7621_DEVICE_xiaomi_mi-router-ac2100=y" >> .config
            ;;
          netgear_r6220)
            echo "CONFIG_TARGET_ramips=y" >> .config
            echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
            echo "CONFIG_TARGET_DEVICE_ramips_mt7621_DEVICE_netgear_r6220=y" >> .config
            ;;
          *)
            echo "未知设备：$DEVICE"
            exit 1
            ;;
        esac

        # 通用配置
        cat >> .config <<'EOF'
        CONFIG_TARGET_ROOTFS_PARTSIZE=256

        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-ssl=y
        CONFIG_PACKAGE_luci-theme-bootstrap=y
        CONFIG_LUCI_LANG_zh_Hans=y
        CONFIG_LUCI_LANG_en=y

        CONFIG_PACKAGE_ca-bundle=y
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_nano=y
        CONFIG_PACKAGE_curl=y
        CONFIG_PACKAGE_wget-ssl=y

        CONFIG_PACKAGE_dnsmasq-full=y
        CONFIG_PACKAGE_firewall=y
        CONFIG_PACKAGE_ip6tables=y
        CONFIG_PACKAGE_iptables=y
        CONFIG_PACKAGE_miniupnpd-iptables=y

        CONFIG_IMAGEOPT=y
        CONFIG_VERSIONOPT=y
        CONFIG_VERSION_MANUFACTURER="Kwrt"
        CONFIG_VERSION_FILENAMES=n
        EOF

    - name: Build OpenWrt
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc)

    - name: Upload firmware as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.DEVICE }}-firmware
        path: openwrt/bin/targets/**/*
