name: OpenWrt-AutoBuild

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: devices/common/.config
  DIY_SH: devices/common/diy.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget curl jq

    - name: Clone source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt

    - name: Update & install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Remove extra LuCI links
      working-directory: ./openwrt
      run: |
        sed -i '/固件下载/d' $(grep -rl "固件下载" package/ feeds/ || true)
        sed -i '/定制/d'     $(grep -rl "定制" package/ feeds/ || true)
        sed -i '/赞助/d'     $(grep -rl "赞助" package/ feeds/ || true)
        sed -i '/TG频道/d'   $(grep -rl "TG频道" package/ feeds/ || true)
        sed -i '/源码与反馈/d' $(grep -rl "源码与反馈" package/ feeds/ || true)

    - name: Load custom configuration
      working-directory: ./openwrt
      run: |
        [ -e $GITHUB_WORKSPACE/$CONFIG_FILE ] && cp $GITHUB_WORKSPACE/$CONFIG_FILE .config
        [ -e $GITHUB_WORKSPACE/$DIY_SH ] && bash $GITHUB_WORKSPACE/$DIY_SH

    - name: Download package
      working-directory: ./openwrt
      run: |
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile firmware
      working-directory: ./openwrt
      run: |
        make -j$(nproc) || make -j1 V=s

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true'
      with:
        name: OpenWrt_firmware
        path: openwrt/bin/targets/
